secret_key_provider = { InMemory = "snowball2" }

[server]
proxy_port = 8000
api_port = 8080


[api]
base_url = "http://localhost:8080/"
real_ip_header = "X-Real-Ip"
    
[gates]

[gates.example_gate] 
destination = "http://localhost:8000/"
internal_destination = "http://wtfismyip.com/"
orders = [ "hash_cash_order" ]

[orders.hash_cash_order]
descriptions = [{Stub = {is_match = true}}]
access_policy = "Blacklist"
toll_declaration = { Hashcash = {
    expiry = "1h", 
    difficulty = 8
    double_spent_db = { stamp_limit = 10000 }
  }
}
